/* 
 * File:   interrupt_gen_cfg.h
 * Author: hesham
 *
 * Created on January 25, 2024, 7:25 PM
 */

#ifndef INTERRUPT_GEN_CFG_H
#define	INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE 1
//#define INTERRUPT_PRIORITY_LEVELS_ENABLE INTERRUPT_FEATURE_ENABLE
#define INTERRUPT_EXTERNAL_INTx_ENABLE  INTERRUPT_FEATURE_ENABLE
#define INTERRUPT_EXTERNAL_RBx_ENABLE  INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE
#define TIMER0_INTERRUPT_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE


#endif	/* INTERRUPT_GEN_CFG_H */

