/* 
 * File:   internal_interrupt.h
 * Author: hesham
 *
 * Created on January 6, 2024, 5:00 PM
 */

#ifndef INTERNAL_INTERRUPT_H
#define	INTERNAL_INTERRUPT_H

#include"interrupt_config.h"

#if ADC_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_ENABLE()     PIE1bits.ADIE=1
#define ADC_INTERRUPT_DISABLE()    PIE1bits.ADIE=0
#define ADC_INTERRUPT_FLAG_CLEAR() PIR1bits.ADIF=0
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define ADC_HighPrioritySet() IPR1bits.ADIP=1
#define ADC_LowPrioritySet()  IPR1bits.ADIP=0
#endif
#endif


#if TIMER0_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER0_INTERRUPT_ENABLE() INTCONbits.TMR0IE=1
#define TIMER0_INTERRUPT_DISABLE() INTCONbits.TMR0IE=0
#define TIMER0_INTERRUPT_FLAG_CLEAR() INTCONbits.TMR0IF=0
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER0_HighPrioritySet() INTCON2bits.TMR0IP=1
#define TIMER0_LowPrioritySet() INTCON2bits.TMR0IP=0
#endif
#endif

#if TIMER1_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_ENABLE()       PIE1bits.TMR1IE=1 
#define TIMER1_INTERRUPT_DISABLE()      PIE1bits.TMR1IE=0
#define TIMER1_INTERRUPT_FLAG_CLEAR()   PIR1bits.TMR1IF=0
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER1_HighPrioritySet()    IPR1bits.TMR1IP=1
#define TIMER1_LowPrioritySet() IPR1bits.TMR1IP=0
#endif
#endif

#if TIMER2_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER2_INTERRUPT_ENABLE()       PIE1bits.TMR2IE=1 
#define TIMER2_INTERRUPT_DISABLE()      PIE1bits.TMR2IE=0
#define TIMER2_INTERRUPT_FLAG_CLEAR()   PIR1bits.TMR2IF=0
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER2_HighPrioritySet()    IPR1bits.TMR2IP=1
#define TIMER2_LowPrioritySet() IPR1bits.TMR2IP=0
#endif
#endif

#if TIMER3_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER3_INTERRUPT_ENABLE()       PIE2bits.TMR3IE=1 
#define TIMER3_INTERRUPT_DISABLE()      PIE2bits.TMR3IE=0
#define TIMER3_INTERRUPT_FLAG_CLEAR()   PIR2bits.TMR3IF=0
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER3_HighPrioritySet()    IPR2bits.TMR3IP=1
#define TIMER3_LowPrioritySet() IPR2bits.TMR3IP=0
#endif
#endif

#if CCP1_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
#define CCP1_INTERRUPT_ENABLE()       PIE1bits.CCP1IE=1 
#define CCP1_INTERRUPT_DISABLE()      PIE1bits.CCP1IE=0
#define CCP1_INTERRUPT_FLAG_CLEAR()  PIR1bits.CCP1IF=0
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define CCP1_HighPrioritySet()    IPR1bits.CCP1IP=1
#define CCP1_LowPrioritySet()     IPR1bits.CCP1IP=0
#endif
#endif


#if CCP2_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
#define CCP1_INTERRUPT_ENABLE()       PIE2bits.CCP2IE=1 
#define CCP1_INTERRUPT_DISABLE()      PIE2bits.CCP2IE=0
#define CCP1_INTERRUPT_FLAG_CLEAR()  PIR2bits.CCP2IF=0
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define CCP1_HighPrioritySet()    IPR2bits.CCP2IP=1
#define CCP1_LowPrioritySet()     IPR2bits.CCP2IP=0
#endif
#endif



#endif	/* INTERNAL_INTERRUPT_H */

