/* 
 * File:   interrupt_config.h
 * Author: hesham
 *
 * Created on January 6, 2024, 7:54 PM
 */

#ifndef INTERRUPT_CONFIG_H
#define	INTERRUPT_CONFIG_H

#include "interrupt_gen_cfg.h"
#include"../GPIO/GPIO.h"

#define INTERRUPT_OCCUR 1
#define INTERRUPT_NOT_OCCUR 0
#define INTERRUPT_ENABLE 1
#define INTERRUPT_DISABLE 0
#define INTERRUPT_PRIORITY_ENABLE 1
#define INTERRUPT_PRIORITY_DISABLE 0

#if INTERRUPT_PRIORITY_LEVELS_ENABLE==INTERRUPT_FEATURE_ENABLE
#define INTERRUPT_PRIORITY_FEATURE_ENABLE() RCONbits.IPEN=1
#define INTERRUPT_PRIORITY_FEATURE_DISABLE() RCONbits.IPEN=1
#define INTERRUPT_GLOBAL_HIGH_PRIORITY_ENABLE() INTCONbits.GIEH=1
#define INTERRUPT_GLOBAL_HIGH_PRIORITY_DISABLE() INTCONbits.GIEH=0
#define INTERRUPT_GLOBAL_LOW_PRIORITY_ENABLE() INTCONbits.GIEL=1
#define INTERRUPT_GLOBAL_LOW_PRIORITY_DISABLE() INTCONbits.GIEL=0
#else
#define INTERRUPT_GLOBAL_ENABLE() INTCONbits.GIE=1
#define INTERRUPT_GLOBAL_DISABLE() INTCONbits.GIE=0
#define INTERRUPT_PERIPHERAL_ENABLE() INTCONbits.PEIE=1
#define INTERRUPT_PERIPHERAL_DISABLE() INTCONbits.PEIE=0
#endif


typedef enum{
     Interrupt_Low_Priority=0,     
     Interrupt_High_Priority,
}Interrupt_Priority_Levels;

#endif	/* INTERRUPT_CONFIG_H */
